### ISSUE TITLE
1.2.0 breaks query_tweets()

### ISSUE THREAD

**Issue by im-n1** [taspinar/twitterscraper#203]
I do call twitter scraping like

```
tweets = query_tweets(query=" OR ".join(kw_list), begindate=self.start, lang=lang, limit=limit)
```

where:
* `kw_list` is just a list of one or more keywords (I use "#dash")
* `begindate` is `datetime.date` instance
* `lang` is `en`
* `limit` is None

I'm getting this massive exception: https://paste.ofcode.org/YzhKbecE6hWVaSyBaaXpwu
When I downgrade to 1.1.0 everything is OK.

P.S.
This case is from https://github.com/im-n1/karpet library from tests. Feel free to clone the repo and run `pytest -v`.

**Comment by StormFalcon32** [comment]
1.2.0 gives me tons of issues also, thanks for the tip to downgrade. Everything seems to work perfectly fine on 1.1.0

**Comment by gwontaeyong** [comment]
i'm using version 1.1.0 but still have some error on create query.
this problem is related with new update on twitter?

**Comment by StormFalcon32** [comment]
No I have some code running perfectly right now. What's your query tweets look like?

**Comment by gwontaeyong** [comment]
ther query used is '#BTS OR #방탄' and here is code

`import datetime

from twitterscraper import query_tweets

if __name__ == '__main__':

    begin = datetime.datetime(2019, 7, 2)
    end = datetime.datetime(2019, 7, 3)
    list_of_tweets = query_tweets("#BTS OR #방탄", begindate=begin, enddate=end)

    # print the retrieved tweets to the screen:
    for tweet in list_of_tweets:
        print(tweet)
`

and i print out url but when i click that link it does not search anything

- https://twitter.com/search?l=k&q=(%23BTS%20OR%20%23방탄)%20since%3A2017-01-02%20until%3A2017-01-03%20lang%3Ako&src=typed_query

![image](https://user-images.githubusercontent.com/24585750/61921302-a97d6280-af97-11e9-80e9-64e207ffb2d2.png)

**Comment by gwontaeyong** [comment]
oh i missed the url is correct but it still can't scrap the tweet

**Comment by StormFalcon32** [comment]
You have to do print(tweet.text) to see the actual tweet

**Comment by gwontaeyong** [comment]
uhmm..... i expect to print just object fo tweet but it can't 
like this 
![image](https://user-images.githubusercontent.com/24585750/61921586-95863080-af98-11e9-9595-25ef916a5ef3.png)

**Comment by StormFalcon32** [comment]
It's not getting any tweets for some reason. Maybe try a different query or something. I literally have a script running right now which is collecting tweets so I'm not really sure what the issue is caused by.

**Comment by gwontaeyong** [comment]
i change the query to Trump Or Clinton like readme.txt in this repo.
but only 10 tweet, i scrape.

i think as twitter update webpage. to scrape tweet we have to add some action to scroll down i think..

**Comment by StormFalcon32** [comment]
It should already be scrolling down

**Comment by gwontaeyong** [comment]
yes your right. it's my miss.
after change my ip using vpn it's work well.
thank you for attention about this problem

**Comment by StormFalcon32** [comment]
Yeah I'm guessing that twitter blocks your ip if you make too many requests because I'm not getting any tweets anymore. I'll try the vpn

**Comment by Camilo-Lesmes** [comment]
storm, I have the same error. I think it is the ip

**Comment by StormFalcon32** [comment]
Try a VPN and slowing down your requests

**Comment by gwontaeyong** [comment]
do you kno how many requests is proper to prevent ip block?
my goal is collect all tweet form 2006 to now

**Comment by StormFalcon32** [comment]
All tweets? Or all tweets matching a particular search? I usually hit it with poolsize=2 and 2 second delay between each request if I'm collecting all tweets from 2006 matching a particular search. This took around 40 hours to complete, so I ran it on an AWS EC2 instance instead of my own computer. Also, you should probably email me instead of commenting in this thread

**Comment by im-n1** [comment]
> 2 second delay between each request

How do I put a throttling into twitterscraper? From what I know it creates and spawns all the request automatically.

**Comment by taspinar** [comment]
Thank you all for the feedback. 
Version 1.2.0 has indeed been a bad release with a typo which was breaking down twitterscraper and in addition fake_useragent was also causing some problems.

Both of these problems have been solved in 1.3.0 and this version is also using of proxy server while making requests.

Please let me know if version 1.3.0 solves your problems.

**Comment by ctynan8** [comment]
I just uninstalled 1.2.0 and installed 1.1.0 (with Python 3.7) yesterday and so far it is working fine for me for searching for specific words. Wondering about advanced search, though? I know it used to be possible to simply copy and paste part of the link from a Twitter advanced search into terminal to get twitterscraper to run that search, but it seems this no longer works?

**Comment by usamanaveed900** [comment]
tried every version of twitterscraper but the issue remains the same...even used vpn to do it but zero tweets are scrapped and it crashes....it was working properly two days before. Any solution?
 

from twitterscraper import query_tweets
 import datetime as dt
 import pandas as pd

begin_date=dt.date(2019,3,4)
 end_date=dt.date(2019,8,16)

limit=500
 lang='english'

tweets=query_tweets('@HamidMirPAK',begindate=begin_date,enddate=end_date,limit=limit,lang=lang)
 df=pd.DataFrame(t.dict for t in tweets)
 df1 = df[['text']]
 export_csv = df1.to_csv (r'C:/Users/usama/Desktop/123.csv', index = None, header=True)
