### ISSUE TITLE
0 tweets

### ISSUE THREAD

**Issue by etemiz** [taspinar/twitterscraper#296]
INFO: Retrying... (Attempts left: 1)
INFO: Scraping tweets from https://twitter.com/search?f=tweets&vertical=default&q=bitcoin&l=
INFO: Using proxy 181.211.38.62:47911
INFO: Got 0 tweets for bitcoin.

Parsing may be an issue.
Both twitterscraper (0.9.3)  and  (1.4.0) are failing.

**Comment by mickyscreggs** [comment]
Have also been facing this issue. Queries that were returning tweets yesterday are not returning tweets today.

**Comment by ravishankarramakrishnan** [comment]
I'm also facing the Same issue! Yesterday it was parsing well, but today it returns 0 tweets

**Comment by xtr32** [comment]
same here 0 tweets

**Comment by pumpkinw** [comment]
same here

**Comment by tengfei7890** [comment]
Seems Twitter has restricted the connection so that all requests return a page with 
"We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"

**Comment by panoptikum** [comment]
+1. That's bad.

**Comment by hakanyusufoglu** [comment]
> INFO: Retrying... (Attempts left: 1)
> INFO: Scraping tweets from https://twitter.com/search?f=tweets&vertical=default&q=bitcoin&l=
> INFO: Using proxy 181.211.38.62:47911
> INFO: Got 0 tweets for bitcoin.
> 
> Parsing may be an issue.
> Both twitterscraper (0.9.3) and (1.4.0) are failing.

hocam bende bir proje geliştirmiştim projemde ana kısım buna bağlı bu sorunu nasıl düzeltebiliriz

**Comment by hakanyusufoglu** [comment]
I need help

**Comment by toscanopedro** [comment]
same here... anyone has a clue for whats going on?

**Comment by hakanyusufoglu** [comment]
Not yet. I used it for school university project. What will I do during the presentation

**Comment by rubengoeminne** [comment]
> Seems Twitter has restricted the connection so that all requests return a page with
> "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"

Indeed, this can be fixed by modifying the header dictionary in query.py from
`HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
to 
`HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
that should fix the issue.

**Comment by locchipinti** [comment]
> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

It works for me!
Thanks @rubengoeminne, genius!

**Comment by hakanyusufoglu** [comment]
Thanks

> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

I am very thank you. its work.

**Comment by xtr32** [comment]
> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

its work.. thanks

**Comment by toscanopedro** [comment]
hi guys, im a kind of noob and do not have a HEADER in my code... someone can tell how can i implement it?

**Comment by BetoJam** [comment]
> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

Thanks a lot my friend! This worked for me! You are a genius!
Let me share you a beer! Paulaner German Beer? Or Negra Modelo Mexican Beer?

**Comment by BetoJam** [comment]
> hi guys, im a kind of noob and do not have a HEADER in my code... someone can tell how can i implement it?

@toscanopedro The header dictionary: HEADER = {'User-Agent': random.choice(HEADERS_LIST)} is not in your own code, instead it is a line inside the file query.py

Just open the file as TXT, and change the lines, such as @rubengoeminne said. You could to search the file in your PC, maybe it will be foun at the path: C:\ProgramData\Anaconda3\Lib\site-packages\twitterscraper

**Comment by toscanopedro** [comment]
> > hi guys, im a kind of noob and do not have a HEADER in my code... someone can tell how can i implement it?
> 
> @toscanopedro The header dictionary: HEADER = {'User-Agent': random.choice(HEADERS_LIST)} is not in your own code, instead it is a line inside the file query.py
> 
> Just open the file as TXT, and change the lines, such as @rubengoeminne said. You could search the file in your PC, maybe it will be foun at the path: C:\ProgramData\Anaconda3\Lib\site-packages\twitterscraper

THX MAN!!!!

**Comment by pumpkinw** [comment]
> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

The modification no longer works. I changed the header dictionary in query.py and still got 0 tweets.

**Comment by AlexBietrix** [comment]
I faced the same issue. It seems to work now to retrieve the tweets. However I get this error when I want to have user info, using query_user_info : local variable 'user_info' referenced before assignment

**Comment by mardiaz353** [comment]
Yah it is not working for me. Changed that line in query.py and same issue occurs.

**Comment by wal-iston** [comment]
Hi. I have implemented the modification suggested by pumpkinw and the algortihm made progress. It was not scraping anything before modification. But after modification it is scraping, but not everything. It seems it is scraping only some last hours. For example, when I issued:

`
twitterscraper fascismo --lang pt -p 1 -bd 2020-05-31 -ed 2020-06-01 -o file_name.json
`

I received tweets corresponding only to hours from 20 up to 23 of day 2020-05-31:

`
In [12]: df.groupby(df['timestamp'].dt.hour).count()                                                
`
______
Out[12]: 
           has_media  hashtags  img_urls  is_replied  ...  tweet_url  user_id  username  video_url
timestamp                                             ...                                         
20               956       956       956         956  ...        956      956       956        956
21              2384      2384      2384        2384  ...       2384     2384      2384       2384
22              2100      2100      2100        2100  ...       2100     2100      2100       2100
23              2147      2147      2147        2147  ...       2147     2147      2147       2147

[4 rows x 21 columns]
_______

Somebody know what is going on?

**Comment by Frickson** [comment]
already changed the header from HEADER = {'User-Agent': random.choice(HEADERS_LIST)} to 
HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'} but still have the same issue 'NoneType' object has no attribute 'user'.

**Comment by javad94** [comment]
I don't like modifying module's files directly, so instead of that and based on @rubengoeminne 's great answer,  just add these line of codes to the top of your python script:
```python
import twitterscraper
import random
HEADERS_LIST = [
    'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13',
    'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201',
    'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16',
    'Mozilla/5.0 (Windows NT 5.2; RW; rv:7.0a1) Gecko/20091211 SeaMonkey/9.23a1pre'
]
twitterscraper.query.HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}
```
And do your stuff normally:
```python
from twitterscraper import query_tweets
query_tweets("github", 100)
```

**Comment by Marlowe97** [comment]
> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

This solution seems not to work for me now.

**Comment by javad94** [comment]
> > > Seems Twitter has restricted the connection so that all requests return a page with
> > > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> > 
> > 
> > Indeed, this can be fixed by modifying the header dictionary in query.py from
> > `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> > to
> > `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> > that should fix the issue.
> 
> This solution seems not to work for me now.

Yeah, unfortunately they close it down.

**Comment by toscanopedro** [comment]
guys are you sure that you replace the correct arquive? this is still working for me

**Comment by AlexBietrix** [comment]
@toscanopedro where did you replace please ? I replaced in the query.py file, and it's not working...
Thanks !

**Comment by toscanopedro** [comment]
first you  have to pip show twitterscraper to discover the locaticon of the twitterscraper directory. 
the mine was in:
"c:\users\pedro\appdata\local\programs\python\python38-32\lib\site-packages"
inside there is a folder called twitterscraper and the query.py arquive. And you have just to change it.
the path may change, depends what idle you are using. but he is awais inside a "lib\site-packages"

**Comment by AlexBietrix** [comment]
@toscanopedro I am working on GCP, I changed the arquive manually as shown on the picture. Is is sufficient ? 
![Capture d’écran 2020-06-03 à 21 14 04](https://user-images.githubusercontent.com/53409465/83714337-545ea400-a5df-11ea-940b-058504006f2b.png)

Thanks

**Comment by AllanSCosta** [comment]
@toscanopedro it doesn't work on my end, unfortunately. I would imagine that you're making your requests to some server that wasn't updated yet, maybe? I'll play with VPNs and check

**Comment by toscanopedro** [comment]
> @toscanopedro it doesn't work on my end, unfortunately. I would imagine that you're making your requests to some server that wasn't updated yet, maybe? I'll play with VPNs and check

Yes...this is what happen... The problem is back here... my code do not work anymore... its very sad..

**Comment by hakanyusufoglu** [comment]
It doesn't work for me anymore. How to fix?

**Comment by hakanyusufoglu** [comment]
> > @toscanopedro it doesn't work on my end, unfortunately. I would imagine that you're making your requests to some server that wasn't updated yet, maybe? I'll play with VPNs and check
> 
> Yes...this is what happen... The problem is back here... my code do not work anymore... its very sad..

What will we do? the whole project depends on it...

**Comment by toscanopedro** [comment]
> > > @toscanopedro it doesn't work on my end, unfortunately. I would imagine that you're making your requests to some server that wasn't updated yet, maybe? I'll play with VPNs and check
> > 
> > 
> > Yes...this is what happen... The problem is back here... my code do not work anymore... its very sad..
> 
> What will we do? the whole project depends on it...

I dont know... my project depends on it to

**Comment by romit-actuarial** [comment]
> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

Hi everyone 
This was working earlier, but it stopped working today - I think twitter is also following this thread :P 

Help me please - like everyone above my project also depends on it!

**Comment by Marlowe97** [comment]
It seems that Twitter has had it enough! The company is shutting down its original site legacy theme version on the 1st of June 2020.
Twitter has issued a warning to all the users who have been using user-agent switching hacks and unsupported browsers to enable the legacy theme. Since this package is based on the legacy theme and user-agent, I am not sure whether there exists a one-line solution.

**Comment by toscanopedro** [comment]
> It seems that Twitter has had it enough! The company is shutting down its original site legacy theme version on the 1st of June 2020.
> Twitter has issued a warning to all the users who have been using user-agent switching hacks and unsupported browsers to enable the legacy theme. Since this package is based on the legacy theme and user-agent, I am not sure whether there exists a one-line solution.

yes, its true... shit... I think this will take months

**Comment by hakanyusufoglu** [comment]
I was using this library because my Twitter api application was rejected.  Now it's too late for everything.  I hope it gets better soon.

**Comment by sagefuentes** [comment]
I have no idea how useful this is, but I know that Get Old Tweets 3 is still largely working, as of June 4th at 5:18 p.m. PST. It does not have a way to grab video or images (which is why I am interested in twitterscraper). Hopefully this provides use for someone either if they don't need images and videos, or if someone can backwards engineer a solution (I am trying to figure it out, but my chops are not to that level yet).

**Comment by Frickson** [comment]
Is there anyway GetOldTweet can retrieve the total number of retweeted post from the specific user? @sagefuentes

**Comment by lapp0** [comment]
Please try this and let me know how it works for you https://github.com/taspinar/twitterscraper/pull/302

**Comment by vasubhadra** [comment]
It was not working yesterday even after I changed the HEADER in the query.py
But Today all of a sudden its working :)

**Comment by hakanyusufoglu** [comment]
> It was not working yesterday even after I changed the HEADER in the query.py
> But Today all of a sudden its working :)

Yes. very interesting :)

**Comment by toscanopedro** [comment]
same here, guys. its working again... lets see tomorrow

**Comment by Frickson** [comment]
but why I still cannot :C

**Comment by Kai292-tech** [comment]
It works now.

**Comment by Frickson** [comment]
I changed the header in query.py but raise the error "AttributeError: 'NoneType' object has no attribute 'user'", anyone help please..


from twitterscraper.query import query_user_info
import pandas as pd
from multiprocessing import Pool
import time
from IPython.display import display


global twitter_user_info
twitter_user_info=[]


def get_user_info(twitter_user):
    """
    An example of using the query_user_info method
    :param twitter_user: the twitter user to capture user data
    :return: twitter_user_data: returns a dictionary of twitter user data
    """
    user_info = query_user_info(user= twitter_user)
    twitter_user_data = {}
    twitter_user_data["user"] = user_info.user
    twitter_user_data["fullname"] = user_info.full_name
    twitter_user_data["location"] = user_info.location
    twitter_user_data["blog"] = user_info.blog
    twitter_user_data["date_joined"] = user_info.date_joined
    twitter_user_data["id"] = user_info.id
    twitter_user_data["num_tweets"] = user_info.tweets
    twitter_user_data["following"] = user_info.following
    twitter_user_data["followers"] = user_info.followers
    twitter_user_data["likes"] = user_info.likes
    twitter_user_data["lists"] = user_info.lists
    
    return twitter_user_data


def main():
    start = time.time()
    users = ['Carlos_F_Enguix', 'mmtung', 'dremio', 'MongoDB', 'JenWike', 'timberners_lee','ataspinar2', 'realDonaldTrump',
            'BarackObama', 'elonmusk', 'BillGates', 'BillClinton','katyperry','KimKardashian']

    pool = Pool(8)    
    for user in pool.map(get_user_info,users):
        twitter_user_info.append(user)

    cols=['id','fullname','date_joined','location','blog', 'num_tweets','following','followers','likes','lists']
    data_frame = pd.DataFrame(twitter_user_info, index=users, columns=cols)
    data_frame.index.name = "Users"
    data_frame.sort_values(by="followers", ascending=False, inplace=True, kind='quicksort', na_position='last')
    elapsed = time.time() - start
    print(f"Elapsed time: {elapsed}")
    display(data_frame)
    

if __name__ == '__main__':
    main()

**Comment by javad94** [comment]
Great, it's working again. But don't hold your breath on this. Find another alternative before it's too late.

**Comment by lapp0** [comment]
Leaving this open because it appears to be on-and-off working. I'll update #302 so js is *optional* because legacy appears to work *sometimes*

**Comment by lapp0** [comment]
Merged in https://github.com/taspinar/twitterscraper/pull/304 `origin/master` should work now. Please create a new thread if this issue comes up again.

**Comment by GivenToFlyCoder** [comment]
In this moment, TS is working again! 

![New](https://user-images.githubusercontent.com/17298763/83906919-0acea000-a72a-11ea-8db9-06487dcbf00a.png)

**Comment by lapp0** [comment]
https://github.com/taspinar/twitterscraper/pull/304#issuecomment-639691821

**Comment by Frickson** [comment]
cmd>twitterscraper jack -l 50 --user -o jack.json
still return me this errors, why... need help please
INFO: Retrying... (Attempts left: 1)
INFO: Scraping tweets from https://twitter.com/jack
INFO: Using proxy 128.199.202.122:3128
INFO: Got 0 tweets from username jack

python version : 3.7.7
twitterscraper version: 1.4.0

**Comment by lapp0** [comment]
Cannot reproduce with python 3.7.6

Could you paste the beginning of your output before all the retries? mine is.
```
twitterscraper jack -l 50 --user -o jacka.json
INFO: {'User-Agent': 'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko', 'X-Requested-With': 'XMLHttpRequest'}
INFO: Scraping tweets from https://twitter.com/jack
INFO: Using proxy 185.85.219.74:61068
INFO: Scraping tweets from https://twitter.com/i/profiles/show/jack/timeline/tweets?include_available_features=1&include_entities=1&max_position=1268318672319401989&reset_error_state=false
INFO: Using proxy 194.116.162.188:3128
INFO: Scraping tweets from https://twitter.com/i/profiles/show/jack/timeline/tweets?include_available_features=1&include_entities=1&max_position=1268234058263232514&reset_error_state=false
INFO: Using proxy 84.53.247.204:53281
INFO: Scraping tweets from https://twitter.com/i/profiles/show/jack/timeline/tweets?include_available_features=1&include_entities=1&max_position=1267617140292509696&reset_error_state=false
INFO: Using proxy 103.105.77.19:8080
INFO: Got 54 tweets from username jack
```

Could you also run `pip3 freeze` and share the results?

**Comment by Frickson** [comment]
twitterscraper jack -l 50 --user -o jackajson
INFO: {'User-Agent': 'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16'}
INFO: Scraping tweets from https://twitter.com/jack
INFO: Using proxy 102.130.133.102:53281
INFO: Retrying... (Attempts left: 50)
pip3 freeze
chardet==3.0.4
Click==7.0
coala-utils==0.5.1
colorama==0.4.3
configparser==5.0.0
decorator==4.4.2
Django==3.0.7
et-xmlfile==1.0.1
idna==2.9
ipython==7.13.0
ipython-genutils==0.2.0
jdcal==1.4.1
jedi==0.16.0
lxml==4.5.0
numpy==1.18.2
oauthlib==3.1.0
openpyxl==3.0.3
pandas==1.0.3
parso==0.6.2
pickleshare==0.7.5
prompt-toolkit==3.0.5
pycodestyle==2.5.0
Pygments==2.6.1
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2019.3
requests==2.23.0
requests-oauthlib==1.3.0
six==1.14.0
soupsieve==2.0
sqlparse==0.3.1
toml==0.10.0
traitlets==4.3.3
TwitterAPI==2.5.10
twitterscraper==1.4.0
urllib3==1.25.8
wcwidth==0.1.9

**Comment by lapp0** [comment]
@Frickson could you try with a fresh virtualenv?

```
python3 -m venv .venv
source .venv/bin/activate
python3 setup.py install
twitterscraper jack -l 50 --user -o jack.json
```

I'm not sure whether one of your additional packages is causing an issue.

If that doesn't work, I recommend changing https://github.com/taspinar/twitterscraper/blob/master/twitterscraper/query.py#L116 to say
```
except Exception as e:
    logger.exception(e)
````
then share the output

**Comment by Frickson** [comment]
![image](https://user-images.githubusercontent.com/63042203/83953702-f0eda400-a874-11ea-8dc7-547edcf87f0c.png)

**Comment by lapp0** [comment]
Sorry, but I cannot reproduce. By nature of the proxies, I wouldn't expect it to work for me and fail for you... 

You could try https://github.com/taspinar/twitterscraper/pull/302 which uses selenium to fetch tweets.

**Comment by Frickson** [comment]
@lapp0, I already found the error. Thanks you so much.

**Comment by lapp0** [comment]
@Frickson could you share the error in case others come across this problem?

**Comment by lapp0** [comment]
Just an update for anyone coming across this issue: We don't have the recent #304 PR onto pypi yet (@taspinar could you help us out here when you get a chance?).

However, you can resolve this issue by running
```
git clone https://github.com/taspinar/twitterscraper.git
cd twitterscraper

# create virtualenv (optional)
python -m venv .venv
source .venv/bin/activate

# install and run
python3 setup.py install
twitterscraper --user "realDonaldTrump"  --output trump.json
```

**Comment by yousuffarhan** [comment]
> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

Worked for me. Thank you.

**Comment by zhicheng0501** [comment]
> Just an update for anyone coming across this issue: We don't have the recent #304 PR onto pypi yet (@taspinar could you help us out here when you get a chance?).
> 
> However, you can resolve this issue by running
> 
> ```
> git clone https://github.com/taspinar/twitterscraper.git
> cd twitterscraper
> 
> # create virtualenv (optional)
> python -m venv .venv
> source .venv/bin/activate
> 
> # install and run
> python3 setup.py install
> twitterscraper --user "realDonaldTrump"  --output trump.json
> ```

it worked fine days ago. since about 10 days ago, it still failed to pull data.
it returns retrying all the time.

**Comment by anushkmittal** [comment]
getting 0 tweets as well

**Comment by lapp0** [comment]
@zhicheng0501 @anushkmittal please try the `-j` option. Please note that this will be much more expensive in terms of memory, and about 1/2 as fast.

**Comment by kmuhi** [comment]
Thanks:
this fixed it for me:
`HEADER = {'User-Agent': random.choice(HEADERS_LIST),'X-Requested-With': 'XMLHttpRequest'}
`

`INFO: Got 372 tweets (0 new).`

**Comment by OmarxData** [comment]
![image](https://user-images.githubusercontent.com/67119586/85056391-0af18580-b197-11ea-97b7-1b55d15b93da.png)

Ive already edited query.py, not sure what im doing wrong, can anyone help me with this.
still get 0 tweets

**Comment by lapp0** [comment]
@OmarxData are you using `origin/master`? pypi doesn't have latest.

**Comment by zhicheng0501** [comment]
> @OmarxData are you using `origin/master`? pypi doesn't have latest.

Hi, this is what i am facing now.
You told me to try selenium method but it will change the structure of data pulled which would be  a trouble because i have pulled millions of data already. 
I need to keep the same structure of data.
That is why i am trying to make this method happen.


![image](https://user-images.githubusercontent.com/48405087/85227048-4c8b6600-b40d-11ea-842d-7d4de5f395e7.png)

**Comment by Frickson** [comment]
AttributeError: 'NoneType' object has no attribute 'user'
I get this error because Twitterscraper cannot scrape private account??

**Comment by zhicheng0501** [comment]
@lapp0 

Hi, this is what i am facing now.
You told me to try selenium method but it will change the structure of data pulled which would be  a trouble because i have pulled millions of data already. 
I need to keep the same structure of data.
That is why i am trying to make this method happen.


![image](https://user-images.githubusercontent.com/48405087/85227048-4c8b6600-b40d-11ea-842d-7d4de5f395e7.png)

**Comment by lapp0** [comment]
@zhicheng0501 Just to be clear, you have tried `origin/master` first, correct?  I'm getting tweets for `origin/master`'s version without having to use selenium or #302.

If you have indeed tried `origin/master`, you can try #302 and transform the results using the `twitterscraper` provided datastructure `Tweet`.

Please let me know if `origin/master` (not the latest version from pip!) is failing for you.

**Comment by zhicheng0501** [comment]
> @zhicheng0501 Just to be clear, you have tried `origin/master` first, correct? I'm getting tweets for `origin/master`'s version without having to use selenium or #302.
> 
> If you have indeed tried `origin/master`, you can try #302 and transform the results using the `twitterscraper` provided datastructure `Tweet`.
> 
> Please let me know if `origin/master` (not the latest version from pip!) is failing for you.

May i ask how to use origin/master? I have been using pip to install and run the program. Is it wrong to do it this way?

**Comment by jassena** [comment]
guys pls help
![image](https://user-images.githubusercontent.com/63742071/85405752-dda62e00-b52e-11ea-8d52-441da64573fa.png)
![image](https://user-images.githubusercontent.com/63742071/85405851-fca4c000-b52e-11ea-843d-68ac056cfe57.png)

**Comment by jassena** [comment]
im using spyder 4.1.3

**Comment by lapp0** [comment]
@jassena what is your command and full output? (please text, no screenshot)

**Comment by lapp0** [comment]
@zhicheng0501 perhaps you have a conflicting dependency version? Try 
```
python3 -m venv .venv
source .venv/bin/activate
python3 setup.py install
```

**Comment by zhicheng0501** [comment]
> @zhicheng0501 perhaps you have a conflicting dependency version? Try
> 
> ```
> python3 -m venv .venv
> source .venv/bin/activate
> python3 setup.py install
> ```
This is what it shows. 
It seems that i tried  but still failed.
May i ask how to use selenium method?
Would you please give me a clue? I used selenium to parse data before writing coding myself. 
I followed 302 steps and install selenium, geckodriver and firefox. 
What should i do next?
May i ask you to show me a screen of sample code you use to run selenium in this case?
![屏幕快照 2020-06-24 10 24 47](https://user-images.githubusercontent.com/48405087/85491703-91c6b800-b606-11ea-890d-c1324e5310fa.png)

**Comment by zhicheng0501** [comment]
> > @zhicheng0501 perhaps you have a conflicting dependency version? Try
> > 
> > ```
> > python3 -m venv .venv
> > source .venv/bin/activate
> > python3 setup.py install
>

Thanks man
That really works.

**Comment by zhicheng0501** [comment]
> > > @zhicheng0501 perhaps you have a conflicting dependency version? Try
> > > ```
> > > python3 -m venv .venv
> > > source .venv/bin/activate
> > > python3 setup.py install
> > > ```
> 
> Thanks man
> That really works.
> I know what problem i came across these days.
> Twitter blocked the keyword nCoV and Wuhancoronavirus on my end. @lapp0  If possible, you may want to test to see if it is blocked on your end and let me know. That would be helpful. 
> At least on my end, it is what i saw.
> I do not know why but it is what occurred and confused me these days.
> I am writing to Twitter why they block it.
> Once i got a clue, I will let the others know which will help to improve your project.

MOre than that above, would you please tell how to run javascript method in selenium. 
i created a new environment using the method you mentioned above and tried the following code but failed:
twitterscraper trump --javascript -bd 2020-04-01 -ed 2020-04-02 -o trump.json

**Comment by lapp0** [comment]
@Frickson please share your command and output

**Comment by jassena** [comment]
> @jassena what is the _command_ you're running and _full_ output? (please text, no screenshot)

hey i just run the code that u mention above...actually i also got 0 tweets...then i change the query.py header that u just told...at that time i got this error 
![image](https://user-images.githubusercontent.com/63742071/85526073-afc8f400-b5d7-11ea-970f-d79886fb725b.png)
this is my code

**Comment by lapp0** [comment]
@jassena What is "this error"? Please share your code and the full error here http://gist.github.com/

**Comment by Toby-masuku** [comment]
Tried everything, still getting 0

**Comment by lapp0** [comment]
@Toby-masuku are you using `origin/master`? Pip doesn't work.

**Comment by Toby-masuku** [comment]
@lapp0  yes I'm using the origin master

**Comment by zhicheng0501** [comment]
> Tried everything, still getting 0
> 

What is the keyword of your query? I am searching Trump and it works fine. But it fails as i search nCoV and Wuhancoronavirus.

**Comment by Toby-masuku** [comment]
@zhicheng0501  key word climate change

**Comment by lapp0** [comment]
what is your **exact** command and what is your output? Please paste it.

**Comment by zhicheng0501** [comment]
> @zhicheng0501 key word climate change
I used pip install twitterscraper and run this code searching "climate change".
It works just fine.
Just let you know. It is okay on my end. 

Last login: Fri Feb 28 18:20:18 on ttys000
bogon:~ zhaoningning$ twitterscraper "climate change" --lang de --limit 10000000000000000 -bd 2020-04-27 -ed 2020-04-28 -o wuhan04270428.json
INFO: {'User-Agent': 'Mozilla/5.0 (Windows NT 5.2; RW; rv:7.0a1) Gecko/20091211 SeaMonkey/9.23a1pre', 'X-Requested-With': 'XMLHttpRequest'}
INFO: queries: ['climate change since:2020-04-27 until:2020-04-28']
INFO: Querying climate change since:2020-04-27 until:2020-04-28
INFO: Scraping tweets from https://twitter.com/search?f=tweets&vertical=default&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
INFO: Using proxy 103.102.15.90:10714
INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=TWEET-1254687772931129344-1254876447442964480&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
INFO: Using proxy 113.11.156.42:31935
INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=thGAVUV0VFVBaAgLv9ydfF6SIWgMC87d7em-oiEjUAFQAlAFUAFQAA&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
INFO: Using proxy 118.174.196.112:36314
INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=thGAVUV0VFVBaCwL3t67Kf6SIWgMC87d7em-oiEjUAFQAlAFUAFQAA&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
INFO: Using proxy 41.63.170.142:8080
INFO: Twitter returned : 'has_more_items' 
INFO: Got 38 tweets for climate%20change%20since%3A2020-04-27%20until%3A2020-04-28.
INFO: Got 38 tweets (38 new).

**Comment by chanhee-kang** [comment]
@zhicheng0501 
HI, tired with "covid19" as searching query but i failed.. do you know the reason?

**Comment by zhicheng0501** [comment]
> @zhicheng0501
> HI, tired with "covid19" as searching query but i failed.. do you know the reason?

@chanhee-kang 
it seems that covid19 searching works fine on my end at this moment. Could you please try ncov and search date ranging from 5-31 to 6-1 and tell me if it works on your end? it fails here on my end.
When i searched ncov, it worked well but it failed since i parsed a lot of data.
I guess it might trigger some mechanism of twitter.

This is the command and result that i am doing of covid19:
bogon:ncov zhaoningning$ twitterscraper COVID-19 --lang de --limit 100000000 -bd 2020-05-31 -ed 2020-06-01 -o wuhan05310601.json
INFO: {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201', 'X-Requested-With': 'XMLHttpRequest'}
INFO: queries: ['COVID-19 since:2020-05-31 until:2020-06-01']
INFO: Querying COVID-19 since:2020-05-31 until:2020-06-01
INFO: Scraping tweets from https://twitter.com/search?f=tweets&vertical=default&q=COVID-19%20since%3A2020-05-31%20until%3A2020-06-01&l=de
INFO: Using proxy 118.175.93.148:55169
INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=TWEET-1267229970235043842-1267243855260205056&q=COVID-19%20since%3A2020-05-31%20until%3A2020-06-01&l=de
INFO: Using proxy 201.55.160.133:3128
INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=thGAVUV0VFVBaEwLWJtLyNliMWgICmyc_kk5YjEjUAFQAlAFUAFQAA&q=COVID-19%20since%3A2020-05-31%20until%3A2020-06-01&l=de

**Comment by Toby-masuku** [comment]
> @Toby-masuku
> I used pip install twitterscraper and run this code searching "climate change".
> It works just fine.
> Just let you know. It is okay on my end.
> 
> Last login: Fri Feb 28 18:20:18 on ttys000
> bogon:~ zhaoningning$ twitterscraper "climate change" --lang de --limit 10000000000000000 -bd 2020-04-27 -ed 2020-04-28 -o wuhan04270428.json
> INFO: {'User-Agent': 'Mozilla/5.0 (Windows NT 5.2; RW; rv:7.0a1) Gecko/20091211 SeaMonkey/9.23a1pre', 'X-Requested-With': 'XMLHttpRequest'}
> INFO: queries: ['climate change since:2020-04-27 until:2020-04-28']
> INFO: Querying climate change since:2020-04-27 until:2020-04-28
> INFO: Scraping tweets from https://twitter.com/search?f=tweets&vertical=default&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
> INFO: Using proxy 103.102.15.90:10714
> INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=TWEET-1254687772931129344-1254876447442964480&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
> INFO: Using proxy 113.11.156.42:31935
> INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=thGAVUV0VFVBaAgLv9ydfF6SIWgMC87d7em-oiEjUAFQAlAFUAFQAA&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
> INFO: Using proxy 118.174.196.112:36314
> INFO: Scraping tweets from https://twitter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&reset_error_state=false&src=typd&max_position=thGAVUV0VFVBaCwL3t67Kf6SIWgMC87d7em-oiEjUAFQAlAFUAFQAA&q=climate%20change%20since%3A2020-04-27%20until%3A2020-04-28&l=de
> INFO: Using proxy 41.63.170.142:8080
> INFO: Twitter returned : 'has_more_items'
> INFO: Got 38 tweets for climate%20change%20since%3A2020-04-27%20until%3A2020-04-28.
> INFO: Got 38 tweets (38 new).

can you please share your code, Maybe I made a mistake

**Comment by lapp0** [comment]
>I used pip install twitterscraper and run this code searching "climate change".

@zhicheng0501 the pip version worked for you? It doesn't have the headers fix in it. How did you get it to work?

**Comment by lapp0** [comment]
@Toby-masuku looks like you got 38 results. What is the problem?

**Comment by Toby-masuku** [comment]
@lapp0  thats's not me, I got 0

![Screenshot (67)](https://user-images.githubusercontent.com/60424202/85906045-737ed900-b80d-11ea-97aa-01f6adf40735.png)

**Comment by Frickson** [comment]
> @Frickson please share your command and output

Hi lapp0, I run the get_twitter_user_data.py from master/origin and just changed the list of name.

**Here my code**
```
start = time.time()
    users = ['Ms_MeiChing']

    pool = Pool(8)    
    for user in pool.map(get_user_info,users):
        twitter_user_info.append(user)
```

```
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\twitterscraper-1.4.0-py3.7.egg\twitterscraper\query.py", line 323, in query_user_info       
    user_info = query_user_page(INIT_URL_USER.format(u=user))
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\twitterscraper-1.4.0-py3.7.egg\twitterscraper\query.py", line 292, in query_user_page       
    user_info = User.from_html(html)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\twitterscraper-1.4.0-py3.7.egg\twitterscraper\user.py", line 101, in from_html
    return self.from_soup(user_profile_header, user_profile_canopy)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\twitterscraper-1.4.0-py3.7.egg\twitterscraper\user.py", line 57, in from_soup
    tweets = tag_prof_nav.find('span', {'class':"ProfileNav-value"})['data-count']
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\bs4\element.py", line 1321, in __getitem__
    return self.attrs[key]
KeyError: 'data-count'
INFO: Got user information from username Ms_MeiChing
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\Users\Asus\Desktop\twitterscraper\examples\get_twitter_user_data.py", line 20, in get_user_info
    twitter_user_data["user"] = user_info.user
AttributeError: 'NoneType' object has no attribute 'user'
"""
user_data.py", line 53, in <module>
    main()
  File "c:/Users/Asus/Desktop/twitterscraper/examples/get_twitter_user_data.py", line 40, in main
    for user in pool.map(get_user_info,users):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'user'
```

**Comment by erb13020** [comment]
@javad94 

What exactly does this header list do?

HEADERS_LIST = [
    'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13',
    'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201',
    'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16',
    'Mozilla/5.0 (Windows NT 5.2; RW; rv:7.0a1) Gecko/20091211 SeaMonkey/9.23a1pre'
]

**Comment by zhicheng0501** [comment]
> @javad94 
> 
> What exactly does this header list do?
> 
> HEADERS_LIST = [
>     'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13',
>     'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko',
>     'Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201',
>     'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16',
>     'Mozilla/5.0 (Windows NT 5.2; RW; rv:7.0a1) Gecko/20091211 SeaMonkey/9.23a1pre'
> ]

Creat random header list for sending request to the server. It lets the server see requests coming from different client,avoiding being blocked by the server.

**Comment by MaximAbdulatif** [comment]
Just did that, same error 😑




> > Seems Twitter has restricted the connection so that all requests return a page with
> > "We've detected that JavaScript is disabled in your browser. Would you like to proceed to legacy Twitter?"
> 
> Indeed, this can be fixed by modifying the header dictionary in query.py from
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST)}`
> to
> `HEADER = {'User-Agent': random.choice(HEADERS_LIST), 'X-Requested-With': 'XMLHttpRequest'}`
> that should fix the issue.

**Comment by Altimis** [comment]
All twitter scrapers dont seem to work anymore. I tried to use selenium to simply scrap maximum tweets between two chosen dates for given quiries. Check my work on : [Scweet](https://github.com/Altimis/Scweet). let me know if you need any clarification.

**Comment by SulimanLab** [comment]
> All twitter scrapers dont seem to work anymore. I tried to use selenium to simply scrap maximum tweets between two chosen dates for given quiries. Check my work on : [Scweet](https://github.com/Altimis/Scweet). let me know if you need any clarification.

That is bad

**Comment by Altimis** [comment]
> > All twitter scrapers dont seem to work anymore. I tried to use selenium to simply scrap maximum tweets between two chosen dates for given quiries. Check my work on : [Scweet](https://github.com/Altimis/Scweet). let me know if you need any clarification.
> 
> That is bad

Yeah .., but I will do my best to add more features to the resulted csv. Til now I could scrap all the important informations about tweets like username, handle, tweet text, emojis, number of likes ... .  I'll try to extract more useful informations like images links...

**Comment by scherbakovdmitri** [comment]
> All twitter scrapers dont seem to work anymore. I tried to use selenium to simply scrap maximum tweets between two chosen dates for given quiries. Check my work on : [Scweet](https://github.com/Altimis/Scweet). let me know if you need any clarification.

snscrape still works
